apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: channel-carrier
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: channel-carrier
  chart:
    git: ssh://git@github.com/anandbanik/blockchain-automation-framework.git
    ref: wmt
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://13.84.154.208:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.supplychain-net:7050
    channeltx: |-
      CtsDChgKFggCGgYI2dSV/QUiCmFsbGNoYW5uZWwSvgMKuwMKCmFsbGNoYW5uZWwSRhI0CgtBcHBs
      aWNhdGlvbhIlEg4KCmNhcnJpZXJNU1ASABITCg9tYW51ZmFjdHVyZXJNU1ASABoOCgpDb25zb3J0
      aXVtEgAa5AISuAIKC0FwcGxpY2F0aW9uEqgCCAESDgoKY2Fycmllck1TUBIAEhMKD21hbnVmYWN0
      dXJlck1TUBIAGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucyIiCgZBZG1p
      bnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyI1ChRMaWZlY3ljbGVFbmRvcnNlbWVudBIdEhMI
      AxIPCgtFbmRvcnNlbWVudBACGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3Jz
      ZW1lbnQQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dy
      aXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaJwoKQ29uc29ydGl1bRIZEhcK
      FVN1cHBseUNoYWluQ29uc29ydGl1bQ==